name: LongEval
dependencies:
  - python=3.9
  - python-terrier
  - pip:
    - tqdm
    - -u git+https://github.com/terrier-org/pyterrier.git#egg=python-terrier
    - -u git+https://github.com/terrierteam/pyterrier_colbert
    - xgboost