name: LongEval
dependencies:
  - python=3.8
  - ipykernel
  - pandas=1.5.3
  - seaborn
  - nltk
  - pip:
      - tqdm
      - transformers==3.0.2
      - python-terrier
      - git+https://github.com/terrier-org/pyterrier.git#egg=python-terrier
      - git+https://github.com/terrierteam/pyterrier_colbert
      - git+https://github.com/terrierteam/pyterrier_t5.git
      - git+https://github.com/terrierteam/pyterrier_doc2query.git
      - git+https://github.com/terrierteam/pyterrier_deepct.git
      - xgboost
      - faiss-gpu==1.6.3
      - ranx
      - lightgbm
      - py-cpuinfo
      - gputil
      - -e .
