WT:
  index_name: "index_WT"
  docs: "data/publish/English/Documents/Trec/"
  train:
    topics: "data/publish/English/Queries/train.trec"
    qrels: "data/publish/French/Qrels/train.txt"
  test:
    topics: "data/publish/English/Queries/heldout.trec"
index_dir: "./data/index/"
